[package]
name = "ml_algo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
serde_json = "1.0.118"
serde_derive = "1.0.203"
csv = "1.3.0"
burn = { version = "0.13.2", features = ["train", "tch"] }
plotly = "0.9.0"
chrono = { version = "0.4.38", features = ["serde"]}
